#!/bin/bash

# defining mail name
echo "localhost" > /etc/mailname

[[ -z $DEBUG ]] && DEBUG="no"

# update config templates
sed -i "s/{{DB_HOST}}/$DB_HOST/g"         /etc/postfix/mysql-email2email.cf
sed -i "s/{{DB_NAME}}/$DB_NAME/g"         /etc/postfix/mysql-email2email.cf
sed -i "s/{{DB_USER}}/$DB_USER/g"         /etc/postfix/mysql-email2email.cf
sed -i "s/{{DB_PASSWORD}}/$DB_PASSWORD/g" /etc/postfix/mysql-email2email.cf

sed -i "s/{{DB_HOST}}/$DB_HOST/g"         /etc/postfix/mysql-users.cf
sed -i "s/{{DB_NAME}}/$DB_NAME/g"         /etc/postfix/mysql-users.cf
sed -i "s/{{DB_USER}}/$DB_USER/g"         /etc/postfix/mysql-users.cf
sed -i "s/{{DB_PASSWORD}}/$DB_PASSWORD/g" /etc/postfix/mysql-users.cf

sed -i "s/{{DB_HOST}}/$DB_HOST/g"         /etc/postfix/mysql-virtual-alias-maps.cf
sed -i "s/{{DB_NAME}}/$DB_NAME/g"         /etc/postfix/mysql-virtual-alias-maps.cf
sed -i "s/{{DB_USER}}/$DB_USER/g"         /etc/postfix/mysql-virtual-alias-maps.cf
sed -i "s/{{DB_PASSWORD}}/$DB_PASSWORD/g" /etc/postfix/mysql-virtual-alias-maps.cf

sed -i "s/{{DB_HOST}}/$DB_HOST/g"         /etc/postfix/mysql-virtual-mailbox-maps.cf
sed -i "s/{{DB_NAME}}/$DB_NAME/g"         /etc/postfix/mysql-virtual-mailbox-maps.cf
sed -i "s/{{DB_USER}}/$DB_USER/g"         /etc/postfix/mysql-virtual-mailbox-maps.cf
sed -i "s/{{DB_PASSWORD}}/$DB_PASSWORD/g" /etc/postfix/mysql-virtual-mailbox-maps.cf

sed -i "s/{{DB_HOST}}/$DB_HOST/g"         /etc/postfix/mysql-virtual-mailbox-domains.cf
sed -i "s/{{DB_NAME}}/$DB_NAME/g"         /etc/postfix/mysql-virtual-mailbox-domains.cf
sed -i "s/{{DB_USER}}/$DB_USER/g"         /etc/postfix/mysql-virtual-mailbox-domains.cf
sed -i "s/{{DB_PASSWORD}}/$DB_PASSWORD/g" /etc/postfix/mysql-virtual-mailbox-domains.cf

sed -i "s/{{DB_HOST}}/$DB_HOST/g"         /etc/dovecot/dovecot-sql.conf
sed -i "s/{{DB_NAME}}/$DB_NAME/g"         /etc/dovecot/dovecot-sql.conf
sed -i "s/{{DB_USER}}/$DB_USER/g"         /etc/dovecot/dovecot-sql.conf
sed -i "s/{{DB_PASSWORD}}/$DB_PASSWORD/g" /etc/dovecot/dovecot-sql.conf

sed -i "s/{{DEBUG}}/$DEBUG/g"       /etc/dovecot/local.conf

sed -i "s,{{SSL_CERT}},$SSL_CERT_FILE,g" /etc/dovecot/conf.d/ssl.conf
sed -i "s,{{SSL_KEY}},$SSL_KEY_FILE,g"   /etc/dovecot/conf.d/ssl.conf

sed -i "s,{{SSL_CERT}},$SSL_CERT_FILE,g" /etc/postfix/main.cf
sed -i "s,{{SSL_KEY}},$SSL_KEY_FILE,g"   /etc/postfix/main.cf

> /etc/aliases
newaliases
